title: ASPIRE Lab
description: Autonomous Systems, Perception, Intelligence, Robotics, and Exploration
url: "https://aspirelabiith.github.io"
baseurl: ""

theme: jekyll-theme-cayman

# Navigation menu links (top-right)
nav:
  - title: "Home"
    url: /
  - title: "People"
    url: /people
  - title: "Publications"
    url: /publications
  - title: "Projects"
    url: /projects
  - title: "Positions"
    url: /positions

# Optional plugins (supported by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
